version: '3'
services:
  # 个人网站服务
  my-website:
    build: .
    ports:
      - "8080:80"
    networks:
      - todo-network

  # 待办应用服务
  todo-app:
    build: ./todo-app
    ports:
      - "3001:3000"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
